# Generated by Django 5.1.4 on 2024-12-09 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoblrBackend', '0002_user_is_active_user_last_login_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(default='', max_length=255, unique=True)),
                ('currentlyEmployed', models.BooleanField(default=False)),
                ('current_organization', models.CharField(default='', max_length=255, unique=True)),
                ('current_roll', models.CharField(default='', max_length=255, unique=True)),
                ('city', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('githubLink', models.CharField(default='', max_length=255)),
                ('linkedinLink', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JoblrBackend.user')),
            ],
        ),
    ]
