# Generated by Django 5.1.4 on 2024-12-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoblrBackend', '0005_user_city_user_country_user_current_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstLogin',
            field=models.BooleanField(default=True),
        ),
    ]
